# docker-compose.yml (in nexus/ root directory)
version: '3.8'

services:
  # Neo4j Database
  neo4j:
    image: neo4j:5.11
    container_name: nexus-db
    ports:
      - "7474:7474"  # Browser interface
      - "7687:7687"  # Bolt protocol
    environment:
      - NEO4J_AUTH=neo4j/yourpassword  # Change this!
      - NEO4J_dbms_memory_pagecache_size=512M
      - NEO4J_dbms.memory.heap.initial_size=512M
      - NEO4J_dbms_memory_heap_max__size=1G
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    restart: unless-stopped
  
  # NestJS API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: nexus-api
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=yourpassword  # Should match the one above
      - OPENAI_API_KEY=your-openai-key  # Add your key here
      - AI_MODEL_NAME=deepseek-coder  # Or your preferred DeepSeek model
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - /app/node_modules
    depends_on:
      - neo4j
    restart: unless-stopped

volumes:
  neo4j_data:
  neo4j_logs: